### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by Nshiab** [chrislkeller/_tabletop_to_datatables#4]
Hello!

I am not able to fully translate the table in French.

Here is an example on my website:
http://naelshiab.com/special/terrains/terrains.html

As you can see, I've been able to change most of it by modifying the scripts, but I am not able to find where to change "Search" and "Showing 1 to 25 of 1,699 entries".

Any idea?

Thank you! :)

**Comment by chrislkeller** [comment]
@Nshiab: First, apologies for the late response. I never bothered to look at issues as I wasn't notified any were opened.

To complete the translation you will want to bring the [DataTables library you link away to](https://github.com/chrislkeller/projects.chrislkeller.com/blob/master/demos/tabletop_to_datatables/index.html#L47) in the index.html file into your code. Here's a file you can [bring in](https://cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/jquery.dataTables.js) and modify.

If you do a search for "entries" you will find the places where you can change the translation.

And I believe if you search for ```"sSearch": "Search:",``` you will be able to translate that section as well.

Let me know if it works...

Chris K.

**Comment by Nshiab** [comment]
Thank you very much Chris!

It's never too late! :)

2015-06-25 2:46 GMT-04:00 Chris Keller <notifications@github.com>:

> @Nshiab <https://github.com/Nshiab>: First, apologies for the late
> response. I never bothered to look at issues as I wasn't notified any were
> opened.
>
> To complete the translation you will want to bring the DataTables library
> you link away to
> <https://github.com/chrislkeller/projects.chrislkeller.com/blob/master/demos/tabletop_to_datatables/index.html#L47>
> in the index.html file into your code. Here's a file you can bring in
> <https://cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/jquery.dataTables.js>
> and modify.
>
> If you do a search for "entries" you will find the places where you can
> change the translation.
>
> And I believe if you search for "sSearch": "Search:", you will be able to
> translate that section as well.
>
> Let me know if it works...
>
> Chris K.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrislkeller/_tabletop_to_datatables/issues/4#issuecomment-115126978>
> .
>



-- 
Nael Shiab
