### ISSUE TITLE
Google spreadsheets no longer use a key

### ISSUE THREAD

**Issue by grygielny** [chrislkeller/_tabletop_to_datatables#7]
Hi, hoping to use this script/table for a project, but just noticed that Google Spreadsheets doesn't use a key now--it's the full URL. Any help? Thanks

**Comment by chrislkeller** [comment]
@grygielny: Take a look over here at this repo... I believe it's more recent and up-to-date: https://github.com/chrislkeller/projects.chrislkeller.com/tree/master/demos/tabletop_to_datatables

Am going to close this... Let me know if it doesn't solve your problem.
